**1) Escreva um programa para criar um vetor contendo todos os números inteiros pares entre 20 e 90.**

In [1]:
import numpy as np

vetor = np.arange(20,91,2)
print(vetor)

[20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66
 68 70 72 74 76 78 80 82 84 86 88 90]


**2) Escreva um programa que calcula a soma de todos os elementos de um vetor. Utilize a função sum do NumPy.**

In [3]:
import numpy as np

def soma(array):
    resultado = np.sum(array)
    return resultado

n = int(input("Insira o número de linhas do vetor: "))
vetor = np.floor(100*np.random.random((n))) 
print(vetor)
s = soma(vetor)
print(s)

Insira o número de linhas do vetor: 5
[51. 78. 74. 97. 35.]
335.0


**3) Escreva um programa que calcula a soma de todos os elementos de uma matriz.**



In [7]:
import numpy as np

i = int(input("Insira o número de linhas da matriz: "))
j = int(input("Insira o número de colunas da matriz: "))
matriz = np.floor(100*np.random.random((i,j))) 
print(matriz)
r = np.sum(matriz)
print(r)

Insira o número de linhas da matriz: 5
Insira o número de colunas da matriz: 5
[[10. 48. 29. 40. 35.]
 [23. 21. 61. 67. 89.]
 [96. 46. 83. 33. 43.]
 [27. 16. 56. 79.  2.]
 [69. 28.  7. 94. 36.]]
1138.0


**4) Escreva um programa que gere uma matriz NxM contendo números aleatórios entre 0 e 1. Dica: np.random.rand(..)**

In [12]:
import numpy as np

n = int(input("Insira o número de linhas da matriz: "))
m = int(input("Insira o número de colunas da matriz: "))
matriz = np.random.rand(n, m)
print(matriz)

Insira o número de linhas da matriz: 5
Insira o número de colunas da matriz: 5
[[0.41299626 0.60359528 0.76603965 0.19252601 0.05445623]
 [0.41898786 0.05952511 0.84405414 0.84551427 0.16188527]
 [0.42556543 0.89933262 0.99614348 0.73271035 0.79918575]
 [0.11111963 0.55121368 0.03268064 0.39467303 0.82516269]
 [0.78815886 0.89430028 0.91454632 0.4233017  0.6957614 ]]


**5) Escreva um programa que calcule o produto matricial A.B, onde A e B são duas matrizes 6x6 formadas por números aleatórios entre -1 e 1.**

In [13]:
import numpy as np

A = np.random.rand(6, 6)
A = (A*2)-1
print(A)

B = np.random.rand(6, 6)
B = (B*2)-1
print(B)
#M = np.dot(A,B)
M = A.dot(B) 
print(M)

[[-0.81817565 -0.48781858 -0.03816634 -0.45856862 -0.81651682  0.62703065]
 [-0.06458294 -0.6316246  -0.04829811 -0.76018079 -0.12353177  0.79152423]
 [ 0.27291913 -0.99134311  0.84899798 -0.78622283  0.07728464 -0.79443905]
 [ 0.84465292 -0.03794121 -0.01766836  0.59875907 -0.46829297  0.52872693]
 [-0.91764428 -0.97327504  0.32853121 -0.09866376 -0.39488463 -0.16418742]
 [-0.66794369 -0.67014931  0.23504324 -0.99566541 -0.31363272  0.59673937]]
[[ 0.42962834 -0.70560356 -0.43608193  0.11323918  0.73331613 -0.1650518 ]
 [ 0.04844055 -0.98524271 -0.5349427   0.75589208 -0.22815916 -0.95599695]
 [-0.96770237  0.41719936  0.12837421  0.31195169 -0.37992984  0.61346333]
 [ 0.50048382  0.05622746 -0.30046695  0.40058105 -0.4480844   0.75907918]
 [-0.92238756  0.58932971  0.61368785 -0.23821903 -0.45158232 -0.03129931]
 [-0.28317114 -0.56876931 -0.80864841  0.82531487  0.14028547  0.9123896 ]]
[[ 0.00787381  0.17838682 -0.25750204  0.05501987  0.18798469  0.82754355]
 [-0.50225554  0.081984

**6) Escreva uma função que receba como argumento duas matrizes A (NxM) e B (MxP) e retorne o produto matricial C = A.B, com C(NxP), utilizando loops (ou seja, sem utilizar funcionalidades prontas do NumPy). Antes de efetuar a multiplicação sua função deve verificar se as dimensões de A e B são compatíveis com um produto matricial. Compare o resultado da função com A.dot(B) para verificar a sua implementação.**

In [ ]:
import numpy as np

N = int(input())
M = int(input())
P = int(input())

A = np.floor(100*np.random.random((N,M))) 
B = np.floor(100*np.random.random((M,P))) 
l = []
for linha in range(N):
    for coluna in range(P):
        s = 0
        for k in range(M):
            s = s + A[linha][k]*B[k][coluna]
        l.append(s)
C = np.array(l).reshape(N,P)
C2 = A.dot(B)

print(C)
print(C2)
if np.array_equal(C,C2)==True:
    print("Matrizes iguais")

4
4
4
[[ 5747.  7176.  5996. 10360.]
 [ 7550. 11297.  6912. 16077.]
 [ 6611. 15294.  7559. 12603.]
 [10720.  8092. 10377. 18211.]]
[[ 5747.  7176.  5996. 10360.]
 [ 7550. 11297.  6912. 16077.]
 [ 6611. 15294.  7559. 12603.]
 [10720.  8092. 10377. 18211.]]
Matrizes iguais


**7) Crie um vetor de temperaturas em graus Celsius contendo 20 valores entre 10ºC e 90ºC. Calcule em um segundo vetor o valor dessas temperaturas em graus Fahrenheit e imprima-o na tela.**

In [14]:
import numpy as np

C = np.random.randint(10,90, size=(20))
print(C)
F = (C*9/5) + 32
print(F)

[79 85 72 58 46 25 71 12 14 45 11 78 70 27 57 44 28 56 44 64]
[174.2 185.  161.6 136.4 114.8  77.  159.8  53.6  57.2 113.   51.8 172.4
 158.   80.6 134.6 111.2  82.4 132.8 111.2 147.2]


**8) Escreva um programa que, dada uma matriz A, verifique se A é simétrica, isto é, se $A = A^T$. Resolva o problema 1) utilizando loops para varrer cada elemento e 2) utilizando A.T (sintaxe do NumPy para cálculo da matriz transposta).**

In [18]:
import numpy as np

a = np.array([[2,1],[1,2]])

print(a.shape)
print(a.shape[0])
print(a.shape[1])

s = 1
for i in range (a.shape[0]):
    for j in range (a.shape[1]):
        if a[i,j] != a[j,i]:
            s = 0

if s == 1:
    print("Matriz simétrica")
else:
    print("Matriz não simétrica")
print(a)    
print(a==a.T)   

(2, 2)
2
2
Matriz simétrica
[[2 1]
 [1 2]]
[[ True  True]
 [ True  True]]


**9) Escreva um programa que resolva um sistema linear com N equações e N incógnitas, tal que Ax = b. Após encontrar o vetor de soluções x, verifique que A.dot(x) é igual a b. Dica: você pode usar np.random.rand(..) para gerar a matriz A e o vetor b.**

In [22]:
##### import numpy as np

N = int(input())


A = np.floor(100*np.random.rand(N,N)) 
B = np.floor(100*np.random.rand(N,1))
print(A)
Ai = np.linalg.inv(A)
print(Ai)
X = Ai.dot(B)
B2 = A.dot(X)
print(X)

if np.array_equal(np.round(B,2),np.round(B2,2))==True:
    print("Cálculo certo")

2
[[36. 77.]
 [96.  7.]]
[[-0.00098039  0.01078431]
 [ 0.01344538 -0.00504202]]
[[0.32843137]
 [0.78151261]]
Cálculo certo


**10) Escreve um programa que crie um arquivo chamado seno.txt contendo duas colunas: a primeira corresponde a 100 valores entre 0 e 2*pi, e a segunda corresponde ao seno de cada valor da primeira coluna. Salve os valores com 6 casas decimais. Dica: utilize a função np.savetxt(..).**

In [ ]:
import numpy as np
import math

linha1 = 2*math.pi*np.random.random((100))
linha1 = list(linha1)

linha2 = []

for i in range (len(linha1)):
    linha1[i] = linha1[i]
    linha2.append(math.sin(linha1[i]))
    
a = np.array([linha1, linha2])
a = np.transpose(a)
np.savetxt("seno.txt",a, fmt="%.6f")


**11) Escreve um programa que leia o arquivo seno.txt gerado no exercício anterior, armazenando a primeira coluna em um vetor x e a segunda coluna em um vetor f. Dica: utilize a função numpy.loadtxt(..)**

In [ ]:
import numpy as np

b = np.loadtxt("seno.txt")
x = np.zeros(b.shape[1])
f = np.zeros(b.shape[1])
b = np.transpose(b)
x = b[0]
f = b[1]
